### ISSUE TITLE
Does not appear to install correctly.

### ISSUE THREAD

**Issue by niallmadden** [kingyin3613/ringspy#1]
I tried to install this on a fresh conda env:

> $ conda create --name ringspy pip
> $ pip install RingsPy [OK]
> <clone https://github.com/kingyin3613/RingsPy>
> $ pytest .
> 

Errors:
```
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-0.13.0
rootdir: /home/<personal>/RingsPy, configfile: pyproject.toml
plugins: hydra-core-1.2.0, cov-3.0.0, mock-3.8.2, anyio-3.6.1
collected 0 items / 4 errors                                                                              
/usr/local/lib/python3.8/dist-packages/coverage/control.py:794: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")

================================================= ERRORS ==================================================
_____________________________ ERROR collecting tests/test_hexalattice_hex.py ______________________________
ImportError while importing test module '/home/<personal>/RingsPy/tests/test_hexalattice_hex.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_hexalattice_hex.py:19: in <module>
    import RingsPy.MeshGenTools as RPgen
E   ModuleNotFoundError: No module named 'RingsPy'

```

**Comment by kingyin3613** [comment]
@niallmadden Thanks for letting me know this issue.

I think this happened because the package was installed in the wrong environment. It is like `pip install` installs the packages within Python environment and `conda install` installs the packages within conda environment, and you are using conda environment indeed. See this thread for more details: https://stackoverflow.com/questions/56134588/is-that-a-bad-idea-to-use-conda-and-pip-install-on-the-same-environment. 

However, I did publish RingsPy to conda-forge channel, so a better way to install is, use the following command to install this package directly from conda:
> conda install -c conda-forge ringspy

and then 
> pytest .

**Comment by niallmadden** [comment]
I'm familar with that issue; installing pip within conda usually resolves it.
I created a new conda environment, and installed with "conda install -c conda-forge ringspy"
I observed the same issue as above. Minimally:

$ "python -c "import rinspy"                                       
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'rinspy

Same result when I deactivate conda, and just use pip install; installs without error, but still can't be found.
Even tried in docker container.

**Comment by kingyin3613** [comment]
I tried create a new conda environment and install within that environment as well and it seems that use of capitalized package name worked fine. Try this:

> "python -c "import RingsPy"

This is weird, but please let me know if this works for you. I will try to fix this problem for the newer releases.

**Comment by niallmadden** [comment]
OK; that worked. Thanks! Would be good to change to more standard module-naming convention: https://peps.python.org/pep-0008/#package-and-module-names

FYI, "tests$ pytest ." fails for test_read_existing_sites.py; passes the other 3.
